export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'
export const GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS'
export const GET_ACCESS_TOKEN_FAILURE = 'GET_ACCESS_TOKEN_FAILURE'

export const POST_SIGN_UP_INFO = 'POST_SIGN_UP'
export const POST_SIGN_UP_INFO_SUCCESS = 'POST_SIGN_UP_SUCCESS'
export const POST_SIGN_UP_INFO_FAILURE = 'POST_SIGN_UP_FAILURE'
