export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

export const GET_PRODUCT_CATEGORY_INFO = 'GET_PRODUCT_CATEGORY_INFO'
export const GET_PRODUCT_CATEGORY_INFO_SUCCESS = 'GET_PRODUCT_CATEGORY_INFO_SUCCESS'
export const GET_PRODUCT_CATEGORY_INFO_FAILURE = 'GET_PRODUCT_CATEGORY_INFO_FAILURE'
