export const GET_PRODUCT_RELATED = 'GET_PRODUCT_RELATED'
export const GET_PRODUCT_RELATED_SUCCESS = 'GET_PRODUCT_RELATED_SUCCESS'
export const GET_PRODUCT_RELATED_FAILURE = 'GET_PRODUCT_RELATED_FAILURE'
