export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE'

export const GET_PRODUCT_RELATED = 'GET_PRODUCT_RELATED'
export const GET_PRODUCT_RELATED_SUCCESS = 'GET_PRODUCT_RELATED_SUCCESS'
export const GET_PRODUCT_RELATED_FAILURE = 'GET_PRODUCT_RELATED_FAILURE'

export const GET_PRODUCT_FILTER_BY_CATEGORY = 'GET_PRODUCT_FILTER_BY_CATEGORY'
export const GET_PRODUCT_FILTER_BY_CATEGORY_SUCCESS =
  'GET_PRODUCT_FILTER_BY_CATEGORY_SUCCESS'
export const GET_PRODUCT_FILTER_BY_CATEGORY_FAILURE =
  'GET_PRODUCT_FILTER_BY_CATEGORY_FAILURE'

export const GET_PRODUCT_FILTER_BY_NAME = 'GET_PRODUCT_FILTER_BY_NAME'
export const GET_PRODUCT_FILTER_BY_NAME_SUCCESS =
  'GET_PRODUCT_FILTER_BY_NAME_SUCCESS'
export const GET_PRODUCT_FILTER_BY_NAME_FAILURE =
  'GET_PRODUCT_FILTER_BY_NAME_FAILURE'

export const GET_PRODUCT_POSTED = 'GET_PRODUCT_POSTED'
export const GET_PRODUCT_POSTED_SUCCESS = 'GET_PRODUCT_POSTED_SUCCESS'
export const GET_PRODUCT_POSTED_FAILURE = 'GET_PRODUCT_POSTED_FAILURE'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE'
